# Generated by Django 5.0.2 on 2024-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealuser',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dealuser',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
