# Generated by Django 5.0.2 on 2024-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('users', '0002_alter_dealuser_lastname_alter_dealuser_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealuser',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='storage.storageunit'),
        ),
    ]
