# Generated by Django 5.0.2 on 2024-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dealuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealuser',
            name='cart',
        ),
        migrations.AddField(
            model_name='dealuser',
            name='cart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
