# Generated by Django 5.0.2 on 2024-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
