# Generated by Django 5.0.2 on 2024-02-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_shortdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=8)),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('photos', models.ManyToManyField(to='core.productphoto')),
            ],
        ),
    ]
