# Generated by Django 5.0.2 on 2024-03-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productphoto_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivered_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('delivering', 'Delivering')], max_length=20)),
                ('products', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
